CREATE DATABASE IF NOT EXISTS sql_crud_api;
USE sql_crud_api;
CREATE TABLE sqlCrudTest( recordId INTEGER PRIMARY KEY AUTO_INCREMENT, textData VARCHAR(256) NOT NULL, creationDate TIMESTAMP DEFAULT NOW() );